# bot/lessons_data.py

IMAGE_LESSONS = {
    1: {
        "title": "Image Generation Basics",
        "description": "Learn to generate masterpieces using text prompts in Midjourney, DALL-E, and Stable Diffusion.",
        "steps": {
            1: "**1. Anatomy of an Image Prompt: More Than Just Words.**\n\nAn image generation prompt is a recipe. Key ingredients:\n- **Subject:** The core of your request. `a majestic cyberpunk wizard`.\n- **Medium:** `digital painting`, `film photograph`, `3D render`.\n- **Style:** `surrealism`, `art deco`, `vaporwave`.\n- **Artist:** `in the style of H.R. Giger`, `in the style of Hayao Miyazaki`.\n- **Composition:** `close-up portrait`, `wide-angle shot`, `dynamic angle`.\n- **Lighting:** `cinematic lighting`, `neon glow`, `god rays`.\n- **Color:** `vibrant contrasting colors`, `monochromatic`, `pastel color palette`.\n- **Details:** `hyperdetailed`, `intricate details`, `4k`, `UHD`.",
            2: "**2. Building a Prompt from Simple to Complex.**\n\n1. *Idea:* `cat`.\n2. *Specification:* `a black cat wearing a tiny witch hat`.\n3. *Add environment:* `...sitting on a pile of ancient books in a dusty library`.\n4. *Set atmosphere (lighting, style):* `...cinematic lighting, moonlight streaming from a window, fantasy art style`.\n5. *Final prompt (putting it all together):* `Epic fantasy digital painting of a mysterious black cat wearing a tiny witch hat, sitting on a pile of ancient books in a dusty library, cinematic lighting, moonlight streaming from a window, intricate details, hyperrealistic, in the style of Greg Rutkowski.`",
            3: "**3. Negative Prompts: Saying What You DON'T Want.**\n\nThis is a critical tool for filtering out unwanted elements. You specify everything you don't want to see. In Midjourney use `--no` parameter, in Stable Diffusion use a separate field.\n*Example:* `a beautiful portrait of a woman --no ugly, deformed, disfigured, extra limbs, blurry, bad anatomy, poorly drawn hands`. This significantly increases the chance of a quality result.",
            4: "**4. Composition Control: Word Weights and Angles.**\n\n- **Word Weights (Midjourney):** Use `::` to indicate importance. `space ship::2 exploring a red planet::1`. The spaceship will be twice as 'important' to the model than the planet.\n- **Camera and Angle:** Use photography terms: `wide angle`, `macro shot`, `drone view`, `first-person view`.",
            5: "**5. Key Control Parameters.**\n\n- **Aspect Ratio (`--ar`):** `--ar 16:9` (for wallpapers), `--ar 9:16` (for stories), `--ar 1:1` (square).\n- **Stylize (`--s` in Midjourney):** Level of 'artistry'. `--s 100` (more literal), `--s 750` (more creative and artistic).\n- **Chaos (`--c` in Midjourney):** Level of 'chaos' or variety in the initial image grid. High values give very different results.\n- **Seed:** Generation 'seed'. By saving the `seed` from a successful image, you can generate very similar images by changing details in the prompt. This is key to creating series of works in one style.",
            6: "**6. Iteration and 'Remixing'.**\n\nDon't stop at the first result. Like an image? Use it as a base. Midjourney has 'Vary' (variations) and 'Remix' functions. In 'Remix' mode you can change the prompt for an already created image to refine details without losing the overall composition. This is a powerful tool for perfecting your work.",
            7: "**7. Inspiration and Analysis.**\n\nThe best way to learn is to analyze others' work. Visit galleries (Midjourney, Lexica.art, Civitai) and don't just look at images - copy and analyze prompts. Create a file where you'll save successful 'chunks' of prompts - descriptions of light, styles, techniques. This is your personal library of 'spells'.",
            8: "**8. Image-to-Image Technique (img2img).**\n\nThis is a process where you give the model not only a text prompt, but also a **starting image**. The model uses it as a base, modifying according to your request. This opens incredible possibilities:\n- **Restyling:** Turn your sketch or photo into a masterpiece in Van Gogh's style.\n- **Editing:** Upload a photo and ask to 'add a hat' or 'change hair color'.\n- **Creating variations:** Upload a successful generation and ask to create similar ones with different details."
        }
    },
    2: {
        "title": "Advanced Midjourney Techniques",
        "description": "Master specific and powerful Midjourney tools for complete control over generation.",
        "steps": {
            1: "**1. Parameters `--weird` and `--tile`.**\n\n- **`--weird`:** This parameter adds an element of surrealism and unusualness to your generations. The higher the value (from 0 to 3000), the stranger and more avant-garde the results. Perfect for finding unique ideas. *Example:* `a portrait of a queen --weird 1000`.\n- **`--tile`:** Creates seamless patterns that can be used for textures, wallpapers, or fabrics. *Example:* `impressionistic flowers --tile`.",
            2: "**2. Style Tuner Function.**\n\nThis is a powerful tool for creating your own unique and consistent style. You give it a prompt, and Midjourney generates dozens of style variations. You choose the ones you like, and the system creates a unique code for you.\n*How to use:* Enter `/tune`, write a prompt. After selecting styles you'll get a code (e.g., `--style 1a2B3c4D`). Now you can add it to any prompts to get images in your signature style.",
            3: "**3. Advanced `Remix` and `Vary (Region)`.**\n\n- **`Remix`:** We've mentioned it, but its power is in the details. Enable Remix mode with `/prefer remix` command. Now when clicking 'Vary' you can not just get a variation, but **completely change the prompt**, keeping the overall composition. You can change background, character, lighting.\n- **`Vary (Region)`:** A button that appears under an enlarged image. It allows you to **select an area on the image and regenerate only it** with a new prompt. This is a game-changer: you can fix unsuccessful hands, change facial expression, add a detail without affecting the rest of the image.",
            4: "**4. Multi-prompting and Advanced Weights.**\n\nYou can mix concepts using `::`.\n- **Simple mixing:** `cat:: dog::` will create a hybrid of cat and dog.\n- **Weights:** `hot::2 dog::-1` will try to create a hot dog while removing features of a regular dog. Negative weights help exclude unwanted concepts. This is a more subtle tool than `--no`.",
            5: "**5. Creating Consistent Characters.**\n\nThis is one of the most difficult tasks. There are two main methods:\n- **`Seed` + `Remix`:** Make a successful character generation. Find out its `seed` (send ✉️ emoji in response to generation). Now use this `seed` in new prompts (`--seed 12345`), changing environment and actions through `Remix`. This will preserve overall style and features.\n- **`Character Reference` (`--cref`):** A new, more powerful function. You upload a character image and use its URL in the prompt: `--cref IMAGE_URL`. Midjourney will try to transfer facial features and character style to the new generation. You can control the strength of 'similarity' with the `--cw` parameter (from 0 to 100).",
            6: "**6. When to Choose Midjourney?**\n\nMidjourney is your choice if you need a **maximally artistic, creative, and often unpredictable result**. It's ideal for concept art, fantasy illustrations, and finding a unique visual style. If your goal is 'magic' and inspiration rather than precise control, start with Midjourney."
        }
    },
    3: {
        "title": "Deep Dive into Stable Diffusion",
        "description": "Master Stable Diffusion for complete control over every aspect of the image.",
        "steps": {
            1: "**1. Stable Diffusion Philosophy: Control Above All.**\n\nIf Midjourney is an artist, then Stable Diffusion is your personal photo studio and workshop. The main thing here is **complete control**. You decide everything: from the exact pose of the model to the smallest style details. This is the choice for those who want to realize a specific vision, not just get a beautiful picture.",
            2: "**2. Prompt Anatomy in SD: Order and Syntax Matter.**\n\nUnlike Midjourney, in SD word order matters greatly. What's at the beginning of the prompt is most important.\n- **Word weights:** Instead of `::` use syntax with parentheses. `(masterpiece:1.2), a beautiful woman` - the word 'masterpiece' will be 20% more important. `[ugly]` - square brackets work as word weakening (weight 0.9 analog).\n- **Concept mixing:** `[cat:dog:0.5]` - for half the generation steps the model will 'think' about a cat, and for the second half - about a dog.\n- **Negative prompt:** Always use a separate field where you write everything that shouldn't be there. This allows creating cleaner and higher quality images.",
            3: "**3. What is LoRA (Low-Rank Adaptation)?**\n\nImagine you have a huge library (this is Stable Diffusion), and you want to teach it to draw in the style of one specific, little-known artist. Instead of retraining the entire library, you create a small 'cheat sheet card' with the features of this style. This is LoRA.\nLoRA are small files (20-200 MB) that 'fine-tune' the main model for a **specific style, character, object, or pose**. You can download thousands of LoRAs from sites like Civitai and combine them to get unique results.",
            4: "**4. What is ControlNet?**\n\nThis is the most powerful technology for composition control. ControlNet allows you to 'copy' a certain aspect from one image (reference) to your new one.\n- **OpenPose:** Copies human pose. You can upload a photo of a dancer, and your generated character will take exactly the same pose.\n- **Canny/Scribble:** Copies contours. You can make a simple sketch, and SD will turn it into a detailed image, preserving your composition.\n- **Depth:** Copies depth map, preserving volume and object placement.",
            5: "**5. Practice: Creating a Photorealistic Portrait.**\n\n*Prompt:* `(photorealistic:1.2), (8k, raw photo), a portrait of a 25 years old woman, sharp focus, detailed skin, cinematic lighting`\n*Negative prompt:* `(deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, 3d, cartoon, anime`\n*Model:* Realistic Vision, Deliberate, etc."
        }
    },
    4: {
        "title": "Flux: New Era of AI Generation (Krea & NightCafe)",
        "description": "Get acquainted with the latest Flux models that combine speed, quality, and simplicity.",
        "steps": {
            1: "**1. Flux - What Is It and Why Is It Better?**\n\nFlux is the latest model architecture from Black Forest Labs, powering many modern services including Krea and NightCafe. Its main advantages:\n- **Speed:** Generation happens almost in real-time.\n- **Language understanding:** Flux understands ordinary, 'human' prompts much better. You no longer need to write `masterpiece, 8k, uhd`. Just describe what you want.\n- **Coherence:** Images turn out more logical and cohesive, with correct anatomy and object interaction.",
            2: "**2. Prompting for Flux: Speak Like to a Human.**\n\nForget about complex Stable Diffusion syntax. With Flux you can write prompts as if giving a task to an assistant.\n- *Old approach (SD):* `(masterpiece:1.2), a robot, sitting on a chair in a bar, cinematic lighting`\n- *New approach (Flux):* `A robot is sitting on a chair inside a dimly lit bar. The scene should have a cinematic feel.`\nFlux understands prepositions, relationships between objects, and the overall atmosphere of the scene perfectly. **The simpler and clearer your prompt, the better the result.**",
            3: "**3. Workshop in Krea.ai: Real-time Magic.**\n\nKrea is the perfect platform for getting acquainted with Flux. Its key feature is **Real-time generation**.\n1. Open Krea.ai.\n2. In the left panel, just start drawing primitive shapes (circle, square) and simultaneously write a prompt (e.g., `A cute, fluffy cat with blue eyes`).\n3. You'll see how the image changes in real-time, adapting to your sketches and text. This is an incredibly intuitive way to create what you need.",
            4: "**4. Workshop in NightCafe: Stylization and Creativity.**\n\nNightCafe also actively uses Flux (and other SD models). It's a great tool for stylization.\n1. Go to NightCafe Studio and click 'Create'.\n2. Select Flux model.\n3. In the 'Prompt' field write what you want to create. For example: `A majestic castle on a floating island during a sunset.`\n4. Below you can select 'Style'. Try applying 'Vibrant' or 'Anime' style.\n5. Click 'Create' and see how Flux combines your request with the selected style.",
            5: "**5. Which Model to Choose: Simple Guide.**\n\n- **Need 'magic' and artistic inspiration?** -> **Midjourney**.\n- **Need complete control over pose, style, and details?** -> **Stable Diffusion** (with LoRA and ControlNet).\n- **Need fast, quality, and predictable result from a simple request?** -> **Flux** (in Krea or NightCafe)."
        }
    }
}

TEXT_LESSONS = {
    1: {
        "title": "Prompt Engineering Basics",
        "description": "Learn how to create effective prompts to get desired results from language models.",
        "steps": {
            1: "**1. What is a Prompt and Why Is It Important?**\n\nA prompt is your direct command, question, or instruction to a neural network. The quality of the model's response depends 90% on the quality of your prompt. This is the most important skill for effective work with AI. Think of yourself as a director, and the neural network as a brilliant but very literal actor who needs extremely clear instructions.",
            2: "**2. GIGO Principle (Garbage In, Garbage Out).**\n\nThis principle means 'Garbage In, Garbage Out'. If your prompt is vague ('tell me about cars'), the answer will be superficial. But if the prompt is specific ('Compare fuel efficiency, maintenance costs, and reliability of Toyota Camry 2.5L and Honda Accord 1.5T 2023 engines for 100,000 km mileage'), the answer will be detailed and useful.",
            3: "**3. Anatomy of the Perfect Prompt: Success Formula.**\n\nAn effective prompt often includes the following components (not necessarily all at once):\n- **Role (Persona):** 'Imagine you are an experienced marketer specializing in SMM for tech startups'.\n- **Task:** 'Develop a one-week content plan for promoting a new AI language learning app'.\n- **Context:** 'Target audience - students and young professionals. Promotion budget - 0. Main platforms - Instagram and TikTok'.\n- **Format:** 'Present the result as a markdown table with columns: Day of week, Post topic, Content type (video, stories, post), Sample text'.\n- **Constraints:** 'Texts should be no longer than 200 words. Don't use banal calls to action. Style - energetic and slightly bold'.",
            4: "**4. Power of Role: Make the Model 'Wear the Hat' of an Expert.**\n\nAssigning a role is not just a request, it's a setting for the model on what knowledge base and speech style to use. This is one of the most powerful tricks.\n*Bad:* 'How to bake bread?'\n*Good:* 'You are a French artisan baker, author of a book on sourdough baking. Write a step-by-step, very detailed recipe for yeast-free bread for an absolute beginner. Warn about the 3 most common mistakes and how to avoid them'.",
            5: "**5. Specificity, Details, and Examples.**\n\nThe neural network can't read your mind. Be extremely specific.\n*Bad:* 'Write about traveling to Italy'.\n*Good:* 'Write a blog post in the style of first-person travel notes about a three-day trip to Rome in November. Focus on lesser-known places worth visiting besides the Colosseum and Vatican. Tell where you tried the best carbonara and why it was special. Volume - 500-600 words. Include subheadings for each day'.",
            6: """**6. Iterative Approach: Sculpt a Masterpiece in Dialogue.**

Never expect a perfect answer on the first try. Great prompts are born in dialogue. Clarify, ask to redo, narrow or expand the request. It's like a sculptor's work.
*Example dialogue:*
1. *You:* 'Suggest ideas for summer vacation'.
2. *Model:* (Gives general ideas: beach, mountains, city).
3. *You:* 'Interesting. Let's focus on active mountain recreation in Europe. Budget - 1500 euros per person for 10 days, including flight from Warsaw. I'm not a climber, interested in medium difficulty trekking'.
4. *Model:* (Suggests specific regions: Dolomites in Italy, Tatras in Slovakia, Pyrenees in Spain).
5. *You:* 'Tell me more about trekking in the Dolomites. What routes are there for 3-4 days with overnight stays in shelters? Make an approximate plan for such a hike'.""",
            7: "**7. Ask the Model to Ask Questions.**\n\nIf you're not sure what details are missing, ask the model to help!\n*Example:* 'I want to launch my podcast. Help me create a concept. Ask me 5-7 clarifying questions that will help you give me the best recommendations on topic, format, and target audience'."
        }
    },
    2: {
        "title": "Advanced Prompting Techniques",
        "description": "Master more complex methods for getting accurate and creative responses.",
        "steps": {
            1: "**1. Chain of Thought (CoT) Technique.**\n\nThis technique makes the model 'think out loud', writing out logical steps before the final answer. This dramatically increases accuracy in tasks requiring reasoning. Activated by a simple phrase.\n*Task:* 'There were 50 visitors in a cafe. An hour later 15 left, but 25 new ones came. Another hour later a third of everyone in the cafe left. How many people remained?'\n*Prompt:* '... [task text] ... **Let's reason step by step.**'\n*Model's answer:* '1. Initially there were 50 people. 2. 15 left, 25 came. Change: +10 people. Became: 50 + 10 = 60 people. 3. A third of 60 left. That's 60 / 3 = 20 people. 4. Remained: 60 - 20 = 40 people. **Answer: 40.**'",
            2: "**2. Few-shot Prompting: Learning on the Fly.**\n\nYou give the model several 'request -> answer' examples so it understands the pattern and applies it. This is incredibly effective for formatting, classification, and data extraction.\n*Example:* 'Translate movie titles into emoji:\n- Jaws -> 🦈🌊😱\n- Forrest Gump -> 🏃♂️🍫🦐\n- The Matrix -> 💊😎💻\n- Lord of the Rings -> ?'\nThe model will likely answer: 💍🌋🧙♂️",
            3: "**3. Zero-shot CoT: Magic of One Phrase.**\n\nThis is a combination of the two previous techniques. Even without examples (zero-shot) you can launch a 'chain of thought'. Just add at the end of your complex question the phrase: **'Let's think step by step'**. This simple phrase significantly improves the quality of answers to logical tasks.",
            4: "**4. Self-Consistency: Choosing the Best of Several Paths.**\n\nThis is an advanced version of CoT. You ask the model not just to think step by step, but to suggest several reasoning options and choose the best one.\n*Example:* '...[complex logical task]... **Think through three different solution options step by step and choose the most logical one.**'\nThis makes the model check itself, which reduces the probability of error.",
            5: "**5. ReAct Technique (Reason + Act): Model as Researcher.**\n\nThis is a complex technique where the model alternates Reasoning and Actions to arrive at an answer. In regular chats this can be imitated by asking the model to make an action plan.\n*Prompt:* 'What are the main reasons for the fall of the Roman Empire? To answer, first make a research plan, defining key areas (economy, politics, social factors, military threats). Then, for each point of the plan, formulate main theses. At the end make a generalizing conclusion.'",
            6: "**6. Structured Output: Require JSON or Markdown.**\n\nTo get data in a convenient format for processing, directly ask the model to format the answer.\n*Example:* 'Extract from the following text [long text about car sale] information about model, year of manufacture, mileage, and price. Provide the answer in JSON format with keys 'model', 'year', 'mileage', 'price'.'",
            7: "**7. 'Tips' for AI?**\n\nRecent studies have shown that promising a 'reward' can improve response quality. It sounds funny, but it works. Try adding at the end of a complex prompt: 'I'll give you a 'tip' of $200 for perfectly done work'. This can motivate the model to put in more 'effort'.",
            8: "**8. Tree of Thoughts (ToT).**\n\nThis is an advanced technique, a development of 'Chain of Thought'. You ask the model not just to follow one reasoning path, but to **explore several 'branches' simultaneously**. The model evaluates intermediate thoughts and chooses the most promising for further development. It's like how a person considers several solution options for a problem.\n*Prompt:* '...[very complex creative or strategic task]... **Break down this problem using the 'Tree of Thoughts' approach. Generate 3 initial ideas, evaluate their strengths and weaknesses, then choose the best one and work it out in detail.**'"
        }
    },
    3: {
        "title": "Common Prompting Mistakes",
        "description": "Learn to avoid traps that prevent getting quality responses from the neural network.",
        "steps": {
            1: "**1. Mistake: Too Vague Request.**\n\nThis is the most common problem. The model can't guess what's in your head.\n- *Bad:* 'Tell me about dogs.'\n- *Good:* 'Write a short article (300 words) for children aged 7-9 about the Golden Retriever breed. Describe their character, care needs, and why they're considered good family dogs.'",
            2: "**2. Mistake: 'First Answer Syndrome'.**\n\nMany users accept the model's first answer as final. This is a mistake. Use the first answer as a draft.\n- *Bad:* Get an answer and copy it.\n- *Good:* Get an answer and say: 'Great, now make the tone more formal', 'Shorten this text by half, leaving only key thoughts', 'Please expand the third point in more detail'.",
            3: "**3. Mistake: Absence of Role.**\n\nA request without a role is a question into the void. A request with a role is a question to an expert.\n- *Bad:* 'How do I save for retirement?'\n- *Good:* 'Imagine you are an independent financial consultant. I'm 30 years old, I earn $50,000 a year. Suggest 3 conservative retirement savings strategies with examples of instruments (deposits, bonds, funds).'",
            4: "**4. Mistake: Overloaded Prompt.**\n\nTrying to solve all problems with one request often leads to the model focusing only on part of the question or giving a superficial answer to everything.\n- *Bad:* 'Write me a content plan, come up with a name for my blog, write the first post, and give promotion advice.'\n- *Good:* Break this into 4 separate, sequential requests, using context from previous answers.",
            5: "**5. Mistake: Ignorance of Output Formats.**\n\nMany don't realize you can ask the model to structure information.\n- *Bad:* 'Compare Python and JavaScript.'\n- *Good:* 'Compare Python and JavaScript by key parameters: typing, main application area, entry threshold for beginners, performance. Present the result as a Markdown table.'",
            6: "**6. Mistake: Ignoring 'Temperature' (Creativity).**\n\nAlthough in most chats you can't directly control the 'temperature' parameter, you can influence it with words. If you need an accurate, factual answer, use words 'exactly', 'facts', 'according to source'. If you need creativity - 'invent', 'imagine', 'create a creative idea'.\n- *For facts:* 'List the capitals of EU countries.'\n- *For creativity:* 'Come up with 5 unusual names for a coffee shop located in a library.'"
        }
    },
    4: {
        "title": "Practical Prompt Applications",
        "description": "Real cases and usage scenarios.",
        "steps": {
            1: "**1. Prompt for Creating a Content Plan.**\n\nImagine you're an SMM manager and need to create a content plan for a travel blog.\n*Prompt:* 'Create a 7-day content plan for an Instagram blog about traveling in Italy. Target audience - youth 18-25 years old. Include posts, stories, and Reels ideas in the plan. Topics: budget travel, hidden gems, and local cuisine. Present the result as a Markdown table.'",
            2: "**2. Prompt for Writing an Email Newsletter.**\n\nTask: announce the launch of a new online programming course.\n*Prompt:* 'Write text for an email newsletter announcing my new course 'Python for Beginners'. Tone - friendly and motivating. Indicate that the course is suitable for beginners, lasts 6 weeks, and includes practical projects. At the end add a call to action with a link to the course website.'",
            3: "**3. Prompt for Analyzing Customer Reviews.**\n\nYou have 100 reviews of your mobile app. Need to quickly understand the main problems.\n*Prompt:* 'Analyze the following reviews [you can insert up to 10-20 reviews here] about a mobile app. Highlight 3 main problems that users complain about most often, and 3 aspects they like most. Structure the answer as a list.'",
            4: "**4. Prompt for Interview Preparation.**\n\nYou have an interview for a marketer position. Need to prepare for possible questions.\n*Prompt:* 'I'm preparing for an interview for a Junior Marketing Manager position in an IT company. Act as an interviewer and ask me 10 most likely questions. After each of my answers give constructive feedback.'",
            5: "**5. Prompt for Creating a Story Character.**\n\nYou're writing a story and need a vivid main character.\n*Prompt:* 'Create a detailed character description for a fantasy story. Name: Liara. Race: forest elf. She is an exile wielding forbidden shadow magic. Describe her appearance, character, strengths and weaknesses, as well as her main motivation.'",
            6: "**6. Prompt for Code Refactoring and Explanation.**\n\nTask: improve existing code and understand how it works.\n*Prompt:* 'Act as an experienced Python developer. Analyze this script [code is inserted here]. Find potential performance bottlenecks and inefficient sections in it. Suggest an optimized version of the code. Add a comment to each line of the new version explaining what it does and why your solution is better.'",
            7: "**7. Prompt for Creating a Personalized Learning Plan.**\n\nTask: quickly master a new skill.\n*Prompt:* 'I want to learn SQL basics for data analysis. I have zero knowledge. My goal - in 3 weeks be able to write queries with JOIN, GROUP BY, and window functions. I can devote 45 minutes to study every weekday. Make me a step-by-step learning plan for 3 weeks. Present it as a table with columns: Day, Topic, Practical task.'",
            8: "**8. Prompt for Video or Article Summarization.**\n\nTask: quickly get the essence of long material.\n*Prompt:* 'Make a brief summary of this article [article URL] / this YouTube video [video URL]. Highlight 5 key ideas and present them as a bulleted list. At the end write one paragraph with the main conclusion of the material.'"
        }
    }
}
